"""add_audit_logs_table

Revision ID: 16f74fa27da4
Revises: 9670021d2cf1
Create Date: 2026-05-16 11:31:57.167233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f74fa27da4'
down_revision = '9670021d2cf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

