"""add long_description to products

Revision ID: 38c7f89dbb56
Revises: 62c1dea2e853
Create Date: 2026-05-26 15:06:49.897892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38c7f89dbb56'
down_revision = '62c1dea2e853'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('gallery', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('products', sa.Column('artisan', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('weight', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('dimensions', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('materials', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'materials')
    op.drop_column('products', 'year')
    op.drop_column('products', 'dimensions')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'artisan')
    op.drop_column('products', 'gallery')
    # ### end Alembic commands ###

