"""add email verification expiry

Revision ID: 436be5704ae8
Revises: b7a1704c069b
Create Date: 2026-05-06 12:40:35.136545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436be5704ae8'
down_revision = 'b7a1704c069b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token_expires')
    # ### end Alembic commands ###

