"""restore payments audit_logs cart_items

Revision ID: 88a2fc43b0f8
Revises: 9f9584b0c458
Create Date: 2026-05-31 15:42:33.817861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a2fc43b0f8'
down_revision = '9f9584b0c458'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # IMPORTANT: audit_logs is owned by earlier migrations; do NOT recreate it here.
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if not inspector.has_table("payments"):
        op.create_table(
            "payments",
            sa.Column("id", sa.UUID(), nullable=False),
            sa.Column("order_id", sa.UUID(), nullable=True),
            sa.Column("provider", sa.String(length=50), nullable=False),
            sa.Column("provider_transaction_id", sa.String(length=255), nullable=True),
            sa.Column("status", sa.String(length=20), nullable=False),
            sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
            sa.Column("currency", sa.String(length=10), nullable=False),
            sa.Column("phone", sa.String(length=20), nullable=True),
            sa.Column("checkout_request_id", sa.String(length=255), nullable=True),
            sa.Column("mpesa_receipt", sa.String(length=100), nullable=True),
            sa.Column("result_code", sa.String(length=10), nullable=True),
            sa.Column("raw_payload", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(["order_id"], ["orders.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("provider_transaction_id"),
        )

    existing_indexes = []
    if inspector.has_table("payments"):
        try:
            existing_indexes = [i["name"] for i in inspector.get_indexes("payments")]
        except Exception:
            existing_indexes = []

    ix_name = op.f("ix_payments_checkout_request_id")
    if inspector.has_table("payments") and ix_name not in existing_indexes:
        op.create_index(
            ix_name,
            "payments",
            ["checkout_request_id"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # IMPORTANT: audit_logs is owned by earlier migrations; do NOT drop it here.
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if inspector.has_table("payments"):
        op.drop_index(op.f("ix_payments_checkout_request_id"), table_name="payments")
        op.drop_table("payments")
    # ### end Alembic commands ###

