"""initial schema

Revision ID: 8ce1de3e8c17
Revises: 0001
Create Date: 2026-04-20 14:15:17.050241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ce1de3e8c17'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'MERCHANT', 'ADMIN', name='userrole'),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'merchant_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'merchant_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'trusted_devices')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'mfa_backup_codes')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'current_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mfa_backup_codes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mfa_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('trusted_devices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('users', 'merchant_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'merchant_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'MERCHANT', 'ADMIN', name='userrole'),
               server_default=sa.text("'USER'::userrole"),
               nullable=True)
    # ### end Alembic commands ###

