"""add audit_logs table

Revision ID: 9670021d2cf1
Revises: df49334632a0
Create Date: 2026-05-07 20:20:53.241964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9670021d2cf1'
down_revision = 'df49334632a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

