"""add email verification expiry

Revision ID: b7a1704c069b
Revises: 2e3310c886cf
Create Date: 2026-05-06 12:11:16.129860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a1704c069b'
down_revision = '2e3310c886cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

