"""add_merchant_id_to_products

Revision ID: d9bee3d56f04
Revises: c5c953c3fc54
Create Date: 2026-06-07 04:50:42.193239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9bee3d56f04'
down_revision = 'c5c953c3fc54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping_zones')
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'type',
               existing_type=postgresql.ENUM('DIRECT', name='conversationtype'),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('conversations_merchant_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_customer_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['merchant_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['customer_id'], ['id'])
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.add_column('products', sa.Column('merchant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_products_merchant_id'), 'products', ['merchant_id'], unique=False)
    op.create_foreign_key(None, 'products', 'users', ['merchant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_merchant_id'), table_name='products')
    op.drop_column('products', 'merchant_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.alter_column('messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'delivered'::character varying"),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_customer_id_fkey'), 'conversations', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('conversations_merchant_id_fkey'), 'conversations', 'users', ['merchant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversations', 'type',
               existing_type=postgresql.ENUM('DIRECT', name='conversationtype'),
               server_default=sa.text("'DIRECT'::conversationtype"),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('shipping_zones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('base_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('per_kg_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('shipping_zones_pkey')),
    sa.UniqueConstraint('country_code', name=op.f('shipping_zones_country_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###

