"""create users table

Revision ID: f25b1b776150
Revises: 8ce1de3e8c17
Create Date: 2026-04-21 18:44:50.355149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25b1b776150'
down_revision = '8ce1de3e8c17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

